### ISSUE TITLE
No separate highlighting of strings or booleans?

### ISSUE THREAD

**Issue by gerrywastaken** [hjson/vscode-hjson#3] opened 2017-12-28 05:24 UTC
Should strings be a different color from object names? Also should booleans be a different color from numbers?

Here's what I'm seeing:
<img width="200" alt="screen shot 2017-12-28 at 4 23 08 pm" src="https://user-images.githubusercontent.com/71481/34401033-8171042a-ebeb-11e7-9187-9fbaf845d4b3.png">

I was thinking the highlighting rules would be similar to those of https://hjson.org/try.html

**Comment by gerrywastaken** [comment] 2017-12-28 05:28
Oh so I'm using the "Atom One Dark" theme. I just tried disabling it and boolease got a seperate color, but strings were still showing the same as object names.

**Comment by laktak** [comment] 2018-01-02 23:03
I updated to the latest VS Code (1.19.1) but I can't reproduce the issue.

Keys and strings share the same color but numbers should be different from bool.

**Comment by gerrywastaken** [comment] 2018-01-03 23:41
Yeah that seems to be an issue with my theme (see my last comment). So I I'm wondering why strings and keys are the same color as they are different on: https://hjson.org/try.html

I find that much more readable.

**Comment by skavan** [comment] 2018-04-23 21:15
+1
would be nice if hjson mimicked vscode highighting and vscode with comments highlighting.

**Comment by laktak** [comment] 2018-09-14 18:41
Sorry, this project is EOL, see https://hjson.org

**Comment by dqsully** [comment] 2018-09-24 15:07
I just pushed a fix for this issue. @laktak could you publish v1.0.1?

**Comment by laktak** [comment] 2018-09-24 21:26
I've `updated package.json` to 0.3.1 (the old version was 0.3.0) and published it. Thanks!

**Comment by dqsully** [comment] 2018-09-24 21:33
Awesome, thanks!

**Closed as completed** 2018-09-24 21:34 UTC
